---
# playbook.yml - Deploy Nginx Docker container
- name: Deploy Nginx Docker container
  hosts: web
  become: true

  tasks:
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

    - name: Download Docker GPG key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: "0644"

    - name: Add Docker GPG key
      apt_key:
        file: /usr/share/keyrings/docker-archive-keyring.gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Pull Nginx Docker image
      docker_image:
        name: nginx:latest
        source: pull

    - name: Start Nginx Docker container
      docker_container:
        name: nginx-app
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
