---
# playbook.yml - Deploy Nginx Docker container
- name: Deploy Nginx Docker container
  hosts: web
  become: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Installer Docker
      apt:
        name: docker.io
        state: present
        tags: docker

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Pull Nginx Docker image
      docker_image:
        name: nginx:latest
        source: pull

    - name: Start Nginx Docker container
      docker_container:
        name: nginx-app
        image: nginx:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
